### PR TITLE
Get color scheme from browser

### PR DESCRIPTION
**Pull request by demensky**
1. Displays the color scheme as selected in the operating system.
2. Recolors scrollbars to match the theme.

### CODE REVIEW

**Comment by lgpage** [comment]
@demensky thank you for this. I did not know this was possible, so thank you for teaching.
Is this PR ready for review?

I am still in two minds about removing the ability to set/override the theme for this site.
What is considered best practices around this?

**Comment by demensky** [comment]
If there are wishes, I am ready to consider them and finalize the PR.

**Comment by lgpage** [comment]
My only concern is for users like me (who don't / didn't know about this) who end up stuck with the light theme.

So I think first prize would be
- Default the theme to what the user has set in their OS / browser
- Allow the user to change the theme for this site, and persist this to future sessions

If this is not possible, then second price would be to add a note to the FAQ section.

What do you think?

**Comment by demensky** [comment]
I think it is possible to add an override via [`color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) to `<html>` if there is something in `localStorage`.

**Pull request closed without merging**
